#if !canImport(ObjectiveC)
import XCTest

extension ShellOutTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShellOutTests = [
        ("testCapturingErrorWithFileHandle", testCapturingErrorWithFileHandle),
        ("testCapturingErrorWithStringHandle", testCapturingErrorWithStringHandle),
        ("testCapturingOutputWithFileHandle", testCapturingOutputWithFileHandle),
        ("testCapturingOutputWithStringHandle", testCapturingOutputWithStringHandle),
        ("testErrorDescription", testErrorDescription),
        ("testGitCommands", testGitCommands),
        ("testMultipleCallsToStandardError", testMultipleCallsToStandardError),
        ("testMultipleCallsToStandardOut", testMultipleCallsToStandardOut),
        ("testSeriesOfCommands", testSeriesOfCommands),
        ("testSeriesOfCommandsAtPath", testSeriesOfCommandsAtPath),
        ("testSingleCommandAtPath", testSingleCommandAtPath),
        ("testSingleCommandAtPathContainingSpace", testSingleCommandAtPathContainingSpace),
        ("testSingleCommandAtPathContainingTilde", testSingleCommandAtPathContainingTilde),
        ("testSwiftPackageManagerCommands", testSwiftPackageManagerCommands),
        ("testThrowingError", testThrowingError),
        ("testWithArguments", testWithArguments),
        ("testWithInlineArguments", testWithInlineArguments),
        ("testWithoutArguments", testWithoutArguments),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ShellOutTests.__allTests__ShellOutTests),
    ]
}
#endif
